// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MISPIS_LAB.Data;
using System;

namespace MISPIS_LAB.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20171214122216_AddReports")]
    partial class AddReports
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MISPIS_LAB.Models.Auditor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Position");

                    b.HasKey("ID");

                    b.ToTable("Auditors");
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Position");

                    b.HasKey("ID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Incident", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("TypeID");

                    b.HasKey("ID");

                    b.HasIndex("TypeID");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Main", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuditorID");

                    b.Property<int>("AuthorID");

                    b.Property<int>("IncidentID");

                    b.HasKey("ID");

                    b.HasIndex("AuditorID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("IncidentID");

                    b.ToTable("Mains");
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Report", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Corrections");

                    b.Property<int>("IncidentID");

                    b.HasKey("ID");

                    b.HasIndex("IncidentID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Incident", b =>
                {
                    b.HasOne("MISPIS_LAB.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Main", b =>
                {
                    b.HasOne("MISPIS_LAB.Models.Auditor", "Auditor")
                        .WithMany()
                        .HasForeignKey("AuditorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MISPIS_LAB.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MISPIS_LAB.Models.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MISPIS_LAB.Models.Report", b =>
                {
                    b.HasOne("MISPIS_LAB.Models.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
